[package]
name = "stratis-ffi"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>"]
license = "Apache-2.0"

[lib]
name = "stratis_ffi"
crate-type = ["dylib"]

[dependencies]
stratis-shared = { path = "../shared" }
uuid = { version = "^0.3", features = ["v4"]}