[package]
name = "stratis-unity"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>"]
license = "Apache-2.0"

[lib]
name = "stratis_unity"
crate-type = ["dylib"]

[dependencies]
stratis-shared = { path = "../shared" }