[package]
name = "stratis-shared"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>"]
license = "Apache-2.0"

[dependencies]
hmac-sha1 = "^0.1"
uuid = { version = "^0.3", features = ["v4"]}
byteorder = "1"
rand = "0.3.15"